"""Read-only DOCX content import, preserving paragraph order and source hashes."""
import hashlib
import json
import re
from pathlib import Path
import zipfile
from xml.etree import ElementTree as ET

import argparse
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('local_copy', type=Path)
parser.add_argument('versioned_copy', type=Path)
args = parser.parse_args()
sources = [args.local_copy, args.versioned_copy]
ns = {'w': 'http://schemas.openxmlformats.org/wordprocessingml/2006/main',
      'r': 'http://schemas.openxmlformats.org/officeDocument/2006/relationships',
      'a': 'http://schemas.openxmlformats.org/drawingml/2006/main'}
hashes = {str(p): hashlib.sha256(p.read_bytes()).hexdigest() for p in sources}
with zipfile.ZipFile(sources[1]) as z:
    root = ET.fromstring(z.read('word/document.xml'))
    relroot = ET.fromstring(z.read('word/_rels/document.xml.rels'))
    rels = {r.attrib['Id']: r.attrib.get('Target', '') for r in relroot}
    styles = ET.fromstring(z.read('word/styles.xml'))
    style_names = {}
    for style in styles.findall('w:style', ns):
        name = style.find('w:name', ns)
        if name is not None:
            style_names[style.attrib.get('{'+ns['w']+'}styleId', '')] = name.attrib.get('{'+ns['w']+'}val', '')
    blocks = []
    images = []
    media_dir = Path(__file__).resolve().parent.parent / '.cache' / 'source-media'
    media_dir.mkdir(parents=True, exist_ok=True)
    for p in root.findall('.//w:body//w:p', ns):
        txt = ''.join(n.text or '' for n in p.findall('.//w:t', ns))
        for blip in p.findall('.//a:blip', ns):
            target = rels.get(blip.attrib.get('{'+ns['r']+'}embed', ''), '')
            if target.startswith('media/') and 'word/' + target in z.namelist():
                entry = 'word/' + target
                dest_image = media_dir / Path(target).name
                dest_image.write_bytes(z.read(entry))
                images.append({'entry': entry, 'afterParagraph': f'p{len(blocks):04}', 'reviewPath': str(dest_image)})
        if not txt.strip():
            continue
        st = p.find('w:pPr/w:pStyle', ns)
        sid = st.attrib.get('{'+ns['w']+'}val', '') if st is not None else ''
        links = []
        for link in p.findall('.//w:hyperlink', ns):
            target = rels.get(link.attrib.get('{'+ns['r']+'}id', ''), '')
            if target:
                links.append({'text': ''.join(n.text or '' for n in link.findall('.//w:t', ns)), 'url': target})
        blocks.append({'id': f'p{len(blocks)+1:04}', 'style': style_names.get(sid, sid), 'text': txt, 'links': links})
    data = {'version': 'v1.0.4', 'sourceHashes': hashes, 'identical': len(set(hashes.values())) == 1,
            'paragraphCount': len(blocks), 'imageCount': len([n for n in z.namelist() if n.startswith('word/media/')]), 'images': images, 'paragraphs': blocks}
    dest = Path(__file__).resolve().parent.parent / 'docs' / 'sources' / 'ai-entry-map-v1.0.4.json'
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')
    manifest = {'version': data['version'], 'identical': data['identical'],
                'sourceHashes': dict(zip(['local-copy', 'versioned-copy'], hashes.values())),
                'paragraphCount': len(blocks), 'paragraphs': [
                    {'id': p['id'], 'style': p['style'], 'text': p['text'] if p['style'].lower().startswith('heading ') else ''}
                    for p in blocks]}
    (dest.parent.parent / 'source-manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    txtdest = dest.with_suffix('.txt')
    txtdest.write_text('\n'.join(f"[{p['id']}] ({p['style']}) {p['text']}" for p in blocks), encoding='utf-8')
    search_index = {}
    current_topic = None
    for block in blocks:
        heading = re.match(r'^(\d+\.\d+)\s+(.+)', block['text']) if block['style'].lower() == 'heading 3' else None
        if heading:
            current_topic = heading[1]
            search_index[current_topic] = {'title': heading[2], 'terms': []}
        elif block['style'].lower() in ('heading 1', 'heading 2'):
            current_topic = None
        if current_topic:
            cleaned = re.sub(r'https?://\S+', '', block['text'])
            terms = re.findall(r'\b[A-Za-z][A-Za-z0-9_+-]{1,}\b', cleaned)
            search_index[current_topic]['terms'] = sorted(set(search_index[current_topic]['terms'] + terms))
    search_dest = dest.parent.parent.parent / 'src' / 'source-index.ts'
    search_dest.write_text('// Generated by scripts/extract-source.py from the original subsection text.\n'
                          + 'export const topicSourceIndex: Record<string, {title:string;terms:string[]}> = '
                          + json.dumps(search_index, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
    print(json.dumps({'version': data['version'], 'identical': data['identical'], 'paragraphCount': data['paragraphCount'], 'imageCount': data['imageCount']}, ensure_ascii=True))
