import type {ChapterTranslation} from './curriculum-i18n-types';

const topic = (id: string, title: string, summary: string, example: string): ChapterTranslation['topics'][number] => ({
  id, title, summary, example,
});

/** English translation of the existing source adaptation; examples remain teaching scenarios. */
export const englishFoundations: Record<string, ChapterTranslation> = {
  c01: {
    title: 'Mapping an AI system',
    subtitle: 'Why does a refund assistant need more than a model?',
    summary: 'Start with what the user needs to accomplish, then place models, data, rules, tools, and people in their respective roles. Understand how the system works first, and use that map to make sense of new terminology.',
    takeaways: [
      'AI is a field; machine learning, deep learning, and generative models each have their own scope.',
      'Training changes parameters; prompts, conversation history, and retrieved material usually change the current input.',
      'One success demonstrates a capability. Consistent reliability also requires evaluation, constraints, and recovery mechanisms.',
    ],
    topics: [
      topic('1.1', 'The AI family tree', 'Artificial intelligence covers tasks such as recognition, prediction, planning, and generation; it is broader than chatbots. Machine learning learns patterns from data, while deep learning uses multilayer neural networks. Modern generative AI often builds on deep learning, and language models are just one kind of generative model.', 'Label spam classification, image generation, and refund replies as either discriminative or generative tasks. Then decide whether each necessarily requires a language model.'),
      topic('1.2', 'Rules, data, and tools', 'Rule-driven systems encode explicit conditions in code, while data-driven systems let models find patterns in examples. Real products usually combine both, using databases and business tools to supply facts and carry out actions. The model handles the parts suited to probabilistic judgments.', 'Sketch the responsibilities of a refund assistant: the model identifies the intent, an API looks up the order, rules check eligibility, and customer support handles exceptions.'),
      topic('1.3', 'Parameters inside a model', 'Think of a model as a function with many adjustable parameters. Training adjusts them based on errors; ordinary conversations usually do not. Context is the information visible for the current call, while an external knowledge base holds data that can be updated and retrieved independently. Adding a policy document to that knowledge base does not mean it has been trained into the model.', 'When the company publishes a new refund policy, update the retrieval materials and check which version the answer cites. Uploading a file does not mean the model weights have changed.'),
      topic('1.4', 'Training and the current inference', 'Training updates parameters through backpropagation and an optimizer. Inference usually processes new input with fixed parameters. Adding rules, examples, or retrieved material to the context can change this output, but it is not fine-tuning and does not automatically create permanent memory.', 'Give the assistant three examples of refund replies, then start a new conversation without them. Compare whether it keeps the same format, and explain why neither conversation involved training.'),
      topic('1.5', 'The six layers of a system', 'Compute resources perform calculations, data supplies material, models provide predictive capabilities, systems connect retrieval and tools, products focus on user outcomes, and organizations assign responsibilities and boundaries. These six layers affect one another: even a strong model can be held back by outdated knowledge, confused permissions, or slow processes.', 'On a sketch of the refund assistant, label the GPU, policy library, language model, order tools, human handoff entry point, and accountable owner. Map each to one of the six layers.'),
      topic('1.6', 'From capable to dependable', 'Capability asks whether a system can complete a task; reliability asks how often it gets the task right across different situations. You also need to check whether errors can be detected and recovered from, and whether speed and cost suit the business. One impressive demonstration cannot replace that evidence.', 'Give the refund assistant ordinary questions, questions with missing information, and questions involving conflicting policies. Record why it succeeds or fails instead of saving only its best answer.'),
    ],
    quiz: {
      question: 'The latest refund policy is retrieved and sent to the model with the user’s question. What has happened?',
      options: [
        'The model parameters have been updated, which is equivalent to fine-tuning.',
        'Evidence has been added to the current context; the parameters usually have not changed.',
        'All company policies have now become permanent memories inside the model.',
      ],
      answer: 1,
      explanation: 'Retrieval augmentation adds external material to the current input. Training or fine-tuning updates parameters. Whether the policy can be found again later depends on the application’s storage and retrieval mechanisms.',
    },
    sourceHeading: 'Chapter 1 · An AI knowledge map: start with problems, not terminology',
    referenceTitles: [],
  },
  c02: {
    title: 'Machine learning basics',
    subtitle: 'How does a model learn from errors, and how can we tell it has done more than memorize answers?',
    summary: 'Follow samples, predictions, loss, and parameter updates through a training loop. Consider data splits together with business metrics to judge whether the patterns learned during training will work on new problems.',
    takeaways: [
      'Loss provides a training signal; business success still needs separate evaluation.',
      'Use the training set to learn and the validation set to choose. Keep the test set aside until development decisions are complete.',
      'Model size, data quality, and resources jointly affect results; parameter count alone is not enough for comparison.',
    ],
    topics: [
      topic('2.1', 'Parts of the learning loop', 'A sample provides input features and a target label. The model predicts, the loss measures the gap, and the optimizer adjusts parameters accordingly. The ultimate goal of repeated training is to make useful predictions on unseen data: this is generalization.', 'Take “I want to stop next month’s charge” from a de-identified support ticket as the input and “cancel renewal” as its label. Draw the chain from prediction to loss to parameter update.'),
      topic('2.2', 'Where learning signals come from', 'Supervised learning uses labels, unsupervised learning looks for structure in unlabeled data, and self-supervised learning creates prediction targets from the data itself. Reinforcement learning learns a policy for choosing actions through rewards from an environment. A single large model may use several of these approaches at different stages of its lifecycle.', 'Classify learning from manually labeled support tickets as supervised learning, and predicting the next passage of a ticket as self-supervised learning. Do not automatically describe ordinary chatting as real-time reinforcement learning.'),
      topic('2.3', 'Loss, gradients, and updates', 'A gradient describes how small parameter changes affect the loss. Gradient descent updates parameters in a direction that reduces loss, with the learning rate controlling the step size. Backpropagation computes gradients efficiently, while the optimizer determines the updates. Lower loss does not directly mean more accurate refund decisions.', 'Draw “compute loss → calculate gradients through backpropagation → update with the optimizer.” Separately list a business metric: accuracy of refund eligibility decisions.'),
      topic('2.4', 'Batches, epochs, and randomness', 'A batch is a group of samples used for one update; an epoch is one pass through the entire training set. They measure different things. Initialization, sample order, and computation introduce randomness, so experimental comparisons should preserve configurations, data versions, and random seeds.', 'Using 100 support tickets and a batch size of 10, draw the 10 batches in one epoch. Record the data order and training settings in the experiment log.'),
      topic('2.5', 'Protect the test set boundary', 'The training set updates parameters, the validation set helps choose configurations, and the test set estimates generalization after development is complete. Repeatedly checking test results and changing the system turns the test set into development material. Similar answers or samples leaking into training can also cause data leakage.', 'Put duplicate tickets about the same refund event in the same data split, and set the test set aside. Avoid changing the prompt while consulting test answers.'),
      topic('2.6', 'Underfitting and overfitting', 'Underfitting means the model has not learned the training patterns well enough. Overfitting means it has adapted too closely to details and noise in the training samples. Representative data, regularization, early stopping, and strict data splits can help control overfitting. Bias and variance also encourage us to examine both systematic errors and sensitivity to changes in data.', 'If a refund classifier does well on training tickets but performs worse on a new support channel, check the data distribution, duplicate samples, and validation results before deciding to train it more.'),
      topic('2.7', 'Parameters and training settings', 'Parameters are weights learned during training; hyperparameters such as learning rate and batch size are chosen or searched by developers. 7B means approximately 7 billion parameters, not the number of training samples or the context capacity. Scaling a model also requires balancing data and compute budgets.', 'Divide an experiment card into “learned weights” and “settings we choose.” Put model weights in the first group, and learning rate, batch size, and number of layers in the second.'),
      topic('2.8', 'Choose useful metrics', 'An average score can hide the most costly mistakes. Classification metrics should reflect the costs of missed cases and false positives. Generative tasks need several kinds of evidence, including rules, human or model reviews, and task success rates, covering ordinary, boundary, and adversarial cases.', 'For the refund assistant, report both “incorrectly promised a refund” and “wrongly rejected an eligible user,” alongside overall accuracy. Check which failures the overall score hides.'),
    ],
    quiz: {
      question: 'A team changes its prompt after reviewing test-set errors each time. Eventually the test score is very high. How should this be interpreted?',
      options: [
        'The test set has become part of development, so the score may overestimate generalization.',
        'As long as model parameters are unchanged, the test set always remains independent.',
        'The high score proves the system can handle every new user question.',
      ],
      answer: 0,
      explanation: 'Prompts and rules can also overfit samples. Data repeatedly used to choose between approaches is effectively serving as a validation set. A separate test set that has not influenced development is needed.',
    },
    sourceHeading: 'Chapter 2 · Machine learning basics: how models learn from errors',
    referenceTitles: ['Scaling Laws for Neural Language Models', 'Training Compute-Optimal Large Language Models'],
  },
  c03: {
    title: 'Neural networks and representations',
    subtitle: 'How does a sentence become vectors, then the next token?',
    summary: 'Travel from neurons to tokens, embeddings, and Transformers to understand how text enters computation. Representations can capture relationships, but semantic similarity, a long context, or a high attention weight does not automatically make a result factually reliable.',
    takeaways: [
      'Token boundaries depend on the tokenizer; character counts cannot be used directly as token counts.',
      'Embeddings represent inputs, and attention lets positions exchange relevant information.',
      'Context is the workspace for the current computation. Long-term memory is usually stored and retrieved by an external system.',
    ],
    topics: [
      topic('3.1', 'From neurons to networks', 'An artificial neuron takes a weighted sum of inputs and passes it through a nonlinear activation function. Many units connected in layers can learn complex mappings. Weights adjust the influence of inputs, biases shift the result, and hidden layers form internal representations. These mathematical structures do not, by themselves, establish human-like consciousness.', 'Draw a small neuron: multiply two inputs by different weights, add the results and a bias, then label the activation function. Observe how changing a weight changes the output.'),
      topic('3.2', 'Representations in vectors', 'Representation learning lets a network learn how to express inputs through a task. Embeddings turn discrete objects into continuous numerical vectors. These vectors can reflect relationships in usage patterns, but they are not complete dictionary definitions. Later representations in a Transformer also change with the surrounding context.', 'Compare the relationship between “cancel automatic renewal” and “end the subscription,” then add an order number. Semantic retrieval can find similar expressions, but identifiers still need exact checks.'),
      topic('3.3', 'The model’s units of text', 'A tokenizer splits text into tokens, which may be Chinese characters, word fragments, punctuation, or code fragments. Different tokenizers can produce different results. Tokens are converted into vectors and combined with positional information. Costs, context capacity, and generation limits are often measured in tokens.', 'In the Token lab, enter a Chinese sentence, a piece of code, and a mixture of Chinese and English. Observe the teaching illustration of token splitting, then use the target model’s tokenizer to calculate actual usage.'),
      topic('3.4', 'Why attention matters', 'The meaning at one position in a sentence may depend on a distant position. Passing information along a sequence can make long-range relationships harder to handle. Attention lets the current position directly compute how relevant other visible positions are. Transformers use this to organize information exchange and support parallel training.', 'Read “Wang handed the book to Li because he had an exam.” List the words you would consult to interpret “he,” and consider why interpreting a pronoun depends on context.'),
      topic('3.5', 'How Q, K, and V combine information', 'Self-attention produces Q, K, and V from the current representations. Q is matched against K at visible positions to calculate scores; after normalization, those scores weight the aggregation of V. These are computational vectors, not three databases. An attention map alone cannot fully explain why a model reached a conclusion.', 'In the Attention lab, use “updated” as the current position and observe how it gathers information from positions such as “refund” and “policy.” Distinguish the matching scores from the content being combined.'),
      topic('3.6', 'A layer contains more than attention', 'Multi-head attention builds relationships in different representation subspaces. Feed-forward networks add nonlinear transformations, residual connections provide paths for information and gradients, and normalization helps stabilize scales. Repeating these modules forms a deep Transformer, but individual layers cannot simply be assigned exclusive jobs such as grammar or facts.', 'Add four labels to a Transformer layer: information exchange, nonlinear transformation, residual path, and numerical stabilization. Check whether your sketch has left out computation beyond attention.'),
      topic('3.7', 'Follow a sentence through computation', 'Text is first tokenized and assigned IDs, then becomes vectors combined with positional information. Multiple attention and feed-forward layers keep updating these representations. An autoregressive output layer calculates probabilities for the next token; the chosen token joins the context, and generation continues. This describes the computational flow, not a complete explanation of internal thinking.', 'Take “The refund policy has been updated” through “split into tokens → vectors → information exchange → next token.” Identify the input and output at each step.'),
      topic('3.8', 'Encoders, decoders, and masks', 'Encoder-only models usually use both left and right context and are often used for understanding, classification, and extraction. Decoder-only models generate autoregressively from preceding text. Encoder-decoder models encode an input before generating an output, commonly for translation and summarization. A causal mask prevents a position from looking ahead at future answers: training can compute many positions in parallel, while autoregressive generation usually advances one token at a time.', 'Place “classify a support ticket,” “continue a refund reply,” and “translate a policy into English” beside the three typical approaches. Explain that these are common uses, not mutually exclusive limits on their capabilities.'),
      topic('3.9', 'A window is not permanent memory', 'The context window limits how many tokens can be included in a computation. It is a current workspace, not memory automatically written into parameters. A longer window does not guarantee equally effective use of information at every position. Product features for long-term memory usually require external storage, retrieval, and reinsertion into context.', 'Store a summary of the refund assistant’s history as separate state. On the next call, retrieve only relevant order facts instead of assuming the model remembers everything after the conversation closes.'),
      topic('3.10', 'The costs behind the architecture', 'Transformers are well suited to scaling training, capturing long-range relationships, and handling different kinds of sequence representations. The cost of standard attention grows rapidly with sequence length, while autoregressive generation has sequential dependencies. Context, speed, and cost therefore need to be balanced together.', 'Compare asking the assistant to process one policy page with asking it to process an entire handbook. List the possible increases in input processing, attention, and context demands, then decide whether to retrieve the relevant sections first.'),
    ],
    quiz: {
      question: 'The assistant can repeat order information from the previous turn. What is the most reasonable explanation?',
      options: [
        'Every conversation writes the order into the model parameters.',
        'A larger context window automatically provides reliable permanent memory.',
        'The application may have placed past messages or saved state into the current context again.',
      ],
      answer: 2,
      explanation: 'Inference usually does not update parameters. Information from previous turns is often supplied again through message history, summaries, or external storage. Window capacity alone does not provide persistent memory or ensure accurate use of that information.',
    },
    sourceHeading: 'Chapter 3 · Neural networks and Transformers: how text enters a model',
    referenceTitles: ['Attention Is All You Need', 'Neural Machine Translation by Jointly Learning to Align and Translate', 'Original BERT paper'],
  },
  c04: {
    title: 'How large models develop',
    subtitle: 'How does a base model that continues text become an assistant ready for delivery?',
    summary: 'Follow the model lifecycle through data governance, pretraining, post-training, evaluation, and deployment. Distinguish general capabilities, response behavior, and current business facts so you can choose the right way to improve the system.',
    takeaways: [
      'Pretraining learns broad patterns; post-training mainly adjusts instruction responses and behavioral preferences.',
      'Fine-tuning adapts relatively stable behavior, while retrieval and APIs provide facts that can be updated and checked.',
      'More parameters, more computation per answer, or stronger preference ratings cannot individually guarantee task correctness.',
    ],
    topics: [
      topic('4.1', 'From objectives to continuous delivery', 'Chat models often go through objective and budget planning, data governance, pretraining, continued training, instruction fine-tuning, preference alignment, evaluation, and deployment. Teams may combine or repeat some stages. This is a process map, and monitoring and iteration still continue after delivery.', 'On the model lifecycle, mark where the refund assistant’s capabilities came from. Then place company-policy retrieval and the order API in the runtime stage.'),
      topic('4.2', 'Data quality and the data mix', 'Training material needs parsing, deduplication, filtering, and governance for privacy and licensing. Language and domain distributions also need to be balanced; total data volume is not the only goal. Training token counts may include repeated sampling, so they measure something different from the amount of unique text or the number of model parameters.', 'When organizing de-identified support tickets, record their sources, duplicates, and category mix. Check whether filtering has removed every rare but important refund exception.'),
      topic('4.3', 'How prediction develops capabilities', 'Decoder-only pretraining often predicts the next token from the preceding text. Facts, code, grammar, and task demonstrations in the corpus provide learning signals. A local prediction objective can require complex intermediate computations and produce capabilities across many tasks. Fluent continuation still does not guarantee factual correctness or consistent reasoning.', 'Use the same refund policy for text continuation, summarization, and question answering. Observe how shared language capabilities support different outputs, then verify the evidence for each answer.'),
      topic('4.4', 'Foundation, base, and chat models', '“Foundation model” emphasizes a broadly trained model that can be adapted to many tasks. “Base model” often means the pretrained version before chat-oriented post-training. Instruction or chat models receive further post-training on that base. Their architectures may be similar while their response behavior differs; a chat template is not itself a model architecture.', 'Compare how base and instruction versions from the same model family respond to “list the missing information.” Record the versions and chat templates instead of immediately attributing formatting problems to parameter count.'),
      topic('4.5', 'Adaptation and efficient fine-tuning', 'Continued pretraining extends language-model training, domain adaptation uses domain-specific text, and supervised fine-tuning (SFT) and task fine-tuning reinforce desired responses or task patterns. Full fine-tuning updates many parameters, while parameter-efficient fine-tuning (PEFT) trains only a small subset. LoRA adapts weights through low-rank updates, and QLoRA also quantizes the frozen base model. Saving training resources does not automatically fix data quality; frequently changing policies and orders should still lead you to consider retrieval or databases first.', 'If the tone of refund replies is inconsistent, first try clear examples, then evaluate fine-tuning. If the missing information is a policy that took effect today, update the knowledge source and keep citations.'),
      topic('4.6', 'Learn responses from demonstrations', 'Instruction fine-tuning trains on instructions and ideal answers to make task-appropriate outputs more likely; it does not install a separate instruction module. The accuracy and coverage of demonstrations matter more than mechanically increasing their number. Imitating answers also does not necessarily express subtle preferences between multiple possible responses.', 'Prepare refund demonstrations covering answerable questions, missing information, and cases requiring human handling. Check that every ideal answer clearly states its supporting evidence and any gaps.'),
      topic('4.7', 'Adjust behavior using preferences', 'Classic reinforcement learning from human feedback (RLHF) uses human rankings of candidate responses to train a reward model, then adjusts the language model through reinforcement learning. Direct preference optimization (DPO) optimizes directly from pairs of preferred and rejected answers, without an explicit reward model or reinforcement learning loop. Both depend on labeling standards and representative data. Alignment is not a switch that is turned on once and stays complete.', 'Write two candidate answers to the same refund question: one makes a confident promise, and the other explains that evidence is insufficient. Have reviewers compare factual support and helpfulness, rather than ranking by confidence of tone.'),
      topic('4.8', 'Helpful does not mean factual', 'Post-training mainly changes how a model responds. A preferred answer may still lack factual support, and reward signals can encourage surface traits such as verbosity or confidence. Model alignment is only one layer of system protection; the application still has to manage tool permissions, validation, auditing, and incident response.', 'Even if the model politely says “Your refund has been approved,” verify the order, policy, and actual execution result. Pleasant wording is not a business record.'),
      topic('4.9', 'Answers have a compute budget too', 'Test-time compute concerns the resources allocated to an answer after a question arrives. They may support longer reasoning, multiple candidates, or tool-based verification. More computation can increase latency and cost, and a faulty scorer can still choose the wrong answer. Reasoning text produced by a model is not a complete causal explanation of its internal process.', 'Answer a simple policy query directly from retrieval. For a complex refund amount, use a calculation tool and check the rules, then compare whether the extra steps improved the task outcome.'),
      topic('4.10', 'Evaluate throughout the lifecycle', 'Pretraining evaluation tracks loss and capability trends, while post-training checks instruction following and safety. Deployment and live operation also require attention to real tasks, costs, and the distribution of failures. Public benchmarks can be contaminated or specifically optimized for, so keep independent tests, run regression evaluations for each version, and report severe errors separately.', 'Keep a set of refund boundary cases that has not influenced development. Rerun it whenever the model or knowledge-base version changes, and report incorrect refund promises separately.'),
      topic('4.11', 'Run models economically', 'Quantization reduces numerical representation precision, distillation trains a student model to learn from a teacher, pruning reduces structure, and the KV cache reuses previously computed keys and values. Each changes something different. Batching and parallelism also involve tradeoffs between throughput and per-request latency. Deployment choices must consider quality, resources, and service objectives together.', 'List four requirements for the refund assistant: quality, wait time per request, tasks completed per unit of time, and GPU memory. Then evaluate whether compression actually meets the service needs.'),
      topic('4.12', 'Understand what a release opens up', 'A model release may separately make code, weights, training data, training recipes, and licenses available. Downloadable weights do not establish that the other parts are transparent. Choosing an API or self-hosting also requires comparing updates, privacy, operations, cost, and customization one by one.', 'In a selection table, record what is known about weights, code, data, training recipes, and usage permissions. Mark unconfirmed items “needs verification,” then decide whether the model suits the project.'),
      topic('4.13', 'Connect the first four chapters', 'Data provides learning signals; loss, backpropagation, and an optimizer guide parameter updates. Transformers turn tokens into representations and generate sequences. Pretraining and post-training make models better suited to many tasks, but a deliverable product still needs knowledge, tools, rules, and governance.', 'Using no more than ten nodes, draw the refund assistant’s path from “data → model capabilities → runtime evidence and tools → user outcome.” State the input, output, and possible failure at each node.'),
    ],
    quiz: {
      question: 'The refund assistant already uses a consistent tone but does not know the company policy updated today. What should you change first?',
      options: [
        'Add more preference training so it answers more confidently.',
        'Add more reasoning steps to every question so it automatically fills in the policy.',
        'Update traceable policy materials and supply them through retrieval; keep using the API for orders.',
      ],
      answer: 2,
      explanation: 'The missing piece is current facts. Post-training mainly adjusts response behavior, and more computation per answer does not automatically provide a new private policy. Knowledge sources and business tools should supply those facts.',
    },
    sourceHeading: 'Chapter 4 · The large language model training lifecycle: from raw text to a useful assistant',
    referenceTitles: ['Original InstructGPT / RLHF paper', 'Direct Preference Optimization', 'Original LoRA paper'],
  },
};
