// Generated by scripts/extract-source.py from the original subsection text.
export const topicSourceIndex: Record<string, {title:string;terms:string[]}> = {
  "1.1": {
    "title": "“人工智能”不是一种技术",
    "terms": [
      "AI",
      "Artificial",
      "DL",
      "Deep",
      "Generative",
      "Intelligence",
      "LLM",
      "Language",
      "Large",
      "Learning",
      "ML",
      "Machine",
      "Model",
      "token"
    ]
  },
  "1.2": {
    "title": "三种造系统的方法",
    "terms": [
      "AI",
      "LLM"
    ]
  },
  "1.3": {
    "title": "模型到底是什么",
    "terms": [
      "parameters"
    ]
  },
  "1.4": {
    "title": "训练和推理：上学与开卷答题",
    "terms": [
      "in-context",
      "inference",
      "learning",
      "training"
    ]
  },
  "1.5": {
    "title": "AI 系统的六层结构",
    "terms": [
      "AI",
      "Agent",
      "GPU",
      "Prompt"
    ]
  },
  "1.6": {
    "title": "能力、可靠性与智能不是同一个词",
    "terms": [
      "AI"
    ]
  },
  "2.1": {
    "title": "一次机器学习任务的基本构件",
    "terms": [
      "feature",
      "function",
      "generalization",
      "label",
      "loss",
      "model",
      "optimizer",
      "sample"
    ]
  },
  "2.2": {
    "title": "监督、无监督、自监督与强化学习",
    "terms": [
      "token"
    ]
  },
  "2.3": {
    "title": "损失、梯度和梯度下降",
    "terms": [
      "Adam",
      "SGD",
      "backpropagation",
      "gradient",
      "learning",
      "rate",
      "token"
    ]
  },
  "2.4": {
    "title": "批次、轮次与随机性",
    "terms": [
      "batch",
      "epoch"
    ]
  },
  "2.5": {
    "title": "训练集、验证集与测试集",
    "terms": [
      "data",
      "leakage"
    ]
  },
  "2.6": {
    "title": "过拟合、欠拟合与偏差—方差",
    "terms": [
      "overfitting",
      "underfitting"
    ]
  },
  "2.7": {
    "title": "超参数与参数",
    "terms": [
      "Chinchilla",
      "billion",
      "hyperparameters",
      "token"
    ]
  },
  "2.8": {
    "title": "指标不是答案",
    "terms": [
      "AI",
      "F1"
    ]
  },
  "3.1": {
    "title": "从神经元到多层网络",
    "terms": [
      "activation",
      "bias",
      "function",
      "hidden",
      "layer",
      "weight"
    ]
  },
  "3.2": {
    "title": "表示学习与 Embedding",
    "terms": [
      "Embedding",
      "Transformer",
      "embedding",
      "learning",
      "representation",
      "token"
    ]
  },
  "3.3": {
    "title": "Token：模型读的不是“字”也不是“词”",
    "terms": [
      "API",
      "Token",
      "embedding",
      "token",
      "tokenizer"
    ]
  },
  "3.4": {
    "title": "为什么需要注意力",
    "terms": [
      "All",
      "Attention",
      "Is",
      "Need",
      "RNN",
      "Transformer",
      "You",
      "attention",
      "token"
    ]
  },
  "3.5": {
    "title": "自注意力的 Q、K、V 直觉",
    "terms": [
      "Key",
      "Query",
      "Value",
      "self-attention",
      "token"
    ]
  },
  "3.6": {
    "title": "多头、前馈层、残差与归一化",
    "terms": [
      "Transformer",
      "attention",
      "connection",
      "feed-forward",
      "layer",
      "multi-head",
      "network",
      "normalization",
      "residual"
    ]
  },
  "3.7": {
    "title": "一句话怎样走过 Transformer",
    "terms": [
      "Embedding",
      "Token",
      "Tokenizer",
      "Transformer"
    ]
  },
  "3.8": {
    "title": "Encoder、Decoder 与三种典型路线",
    "terms": [
      "Decoder",
      "Encoder",
      "Transformer",
      "causal",
      "decoder",
      "mask",
      "token"
    ]
  },
  "3.9": {
    "title": "上下文窗口与“记忆”",
    "terms": [
      "context",
      "token",
      "window"
    ]
  },
  "3.10": {
    "title": "Transformer 强在哪里，又付出什么代价",
    "terms": [
      "KV",
      "Transformer",
      "cache",
      "token"
    ]
  },
  "4.1": {
    "title": "全流程总览",
    "terms": []
  },
  "4.2": {
    "title": "数据：规模之外还有配比和治理",
    "terms": [
      "epoch",
      "token"
    ]
  },
  "4.3": {
    "title": "预训练：预测下一个 token，得到的为何不只是补全",
    "terms": [
      "Decoder-only",
      "GPT-3",
      "few-shot",
      "one-shot",
      "token",
      "zero-shot"
    ]
  },
  "4.4": {
    "title": "基础模型、基座模型和聊天模型",
    "terms": [
      "base",
      "chat",
      "foundation",
      "instruct",
      "model"
    ]
  },
  "4.5": {
    "title": "持续预训练、领域适配与微调",
    "terms": [
      "Adaptation",
      "LoRA",
      "Low-Rank",
      "PEFT",
      "Prompt",
      "RAG",
      "SFT",
      "continued",
      "domain-adaptive",
      "fine-tuning",
      "pretraining",
      "supervised"
    ]
  },
  "4.6": {
    "title": "指令微调：从会续写到会响应",
    "terms": [
      "SFT",
      "token"
    ]
  },
  "4.7": {
    "title": "偏好对齐、RLHF 与 DPO",
    "terms": [
      "DPO",
      "Direct",
      "Feedback",
      "GPT-3",
      "Human",
      "InstructGPT",
      "Learning",
      "Optimization",
      "Preference",
      "RLHF",
      "Reinforcement",
      "alignment",
      "from"
    ]
  },
  "4.8": {
    "title": "对齐不是知识注入，也不是事实保证",
    "terms": []
  },
  "4.9": {
    "title": "推理模型与测试时计算：回答阶段也能分配预算",
    "terms": [
      "compute",
      "model",
      "reasoning",
      "test-time"
    ]
  },
  "4.10": {
    "title": "评测贯穿生命周期",
    "terms": [
      "Benchmark",
      "Eval"
    ]
  },
  "4.11": {
    "title": "压缩、部署和推理优化",
    "terms": [
      "KV",
      "cache",
      "distillation",
      "pruning",
      "quantization"
    ]
  },
  "4.12": {
    "title": "开放权重不等于开源",
    "terms": [
      "API"
    ]
  },
  "4.13": {
    "title": "把四章压缩成一条因果链",
    "terms": [
      "AI",
      "Transformer",
      "token"
    ]
  },
  "5.1": {
    "title": "Prompt 的基本组成",
    "terms": [
      "JSON",
      "Prompt"
    ]
  },
  "5.2": {
    "title": "消息角色与指令层级",
    "terms": [
      "API",
      "Injection",
      "Prompt",
      "assistant",
      "developer",
      "system",
      "user"
    ]
  },
  "5.3": {
    "title": "上下文窗口是什么",
    "terms": [
      "Prompt",
      "Token",
      "context",
      "window"
    ]
  },
  "5.4": {
    "title": "零样本、少样本与示例",
    "terms": [
      "few-shot",
      "one-shot",
      "zero-shot"
    ]
  },
  "5.5": {
    "title": "结构化输出不只是排版",
    "terms": [
      "JSON",
      "Output",
      "Schema",
      "Structured"
    ]
  },
  "5.6": {
    "title": "Prompt 的迭代方法",
    "terms": [
      "API",
      "Context",
      "OpenAI",
      "Prompt",
      "RAG",
      "vs"
    ]
  },
  "6.1": {
    "title": "一条完整的 RAG 流水线",
    "terms": [
      "PDF",
      "Prompt",
      "RAG",
      "chunk",
      "embedding"
    ]
  },
  "6.2": {
    "title": "Embedding 与向量检索",
    "terms": [
      "AI",
      "BM25",
      "Embedding",
      "Google",
      "ID",
      "RAG",
      "hybrid",
      "reranker",
      "search"
    ]
  },
  "6.3": {
    "title": "Chunking：切得太大和太小都不行",
    "terms": [
      "Chunking",
      "Token",
      "chunk"
    ]
  },
  "6.4": {
    "title": "元数据、权限和版本",
    "terms": [
      "Prompt",
      "RAG",
      "embedding"
    ]
  },
  "6.5": {
    "title": "RAG、微调与长上下文怎么选",
    "terms": [
      "API",
      "RAG",
      "SQL"
    ]
  },
  "6.6": {
    "title": "RAG 不保证不幻觉",
    "terms": [
      "Prompt",
      "RAG",
      "vs"
    ]
  },
  "7.1": {
    "title": "Tool Calling 是什么",
    "terms": [
      "API",
      "Calling",
      "JSON",
      "OpenAI",
      "Schema",
      "Tool",
      "arguments",
      "calling",
      "date",
      "function",
      "person",
      "reschedule_event",
      "time",
      "tool"
    ]
  },
  "7.2": {
    "title": "Agent 到底是什么",
    "terms": [
      "Agent",
      "ReAct"
    ]
  },
  "7.3": {
    "title": "Agent、工作流和聊天机器人",
    "terms": [
      "Agent",
      "OCR"
    ]
  },
  "7.4": {
    "title": "规划、状态与记忆",
    "terms": [
      "Agent",
      "email_draft_id",
      "research_complete",
      "true"
    ]
  },
  "7.5": {
    "title": "多 Agent 并不自动更聪明",
    "terms": [
      "Agent",
      "Token"
    ]
  },
  "7.6": {
    "title": "让 Agent 可控的工程措施",
    "terms": [
      "API",
      "Agent",
      "HTML",
      "Prompt",
      "Schema",
      "Token"
    ]
  },
  "7.7": {
    "title": "GUI Agent 与 Computer Use：操作人类界面",
    "terms": [
      "API",
      "Agent",
      "Computer",
      "DOM",
      "GUI",
      "Tool",
      "Use",
      "calling",
      "vs"
    ]
  },
  "8.1": {
    "title": "为什么传统单元测试不够",
    "terms": [
      "AI",
      "JSON",
      "LLM-as-a-judge",
      "Rubric"
    ]
  },
  "8.2": {
    "title": "从黄金集开始",
    "terms": []
  },
  "8.3": {
    "title": "RAG 和 Agent 应分段评测",
    "terms": [
      "Agent",
      "Evals",
      "OpenAI",
      "RAG",
      "Top-k"
    ]
  },
  "8.4": {
    "title": "离线评测与在线指标",
    "terms": [
      "ID",
      "Prompt",
      "Token"
    ]
  },
  "8.5": {
    "title": "成本：不只是 Token 单价",
    "terms": [
      "AI",
      "API",
      "Agent",
      "Prompt",
      "Token",
      "embedding"
    ]
  },
  "8.6": {
    "title": "延迟与用户体验",
    "terms": [
      "Agent",
      "P50",
      "P95",
      "P99",
      "Token"
    ]
  },
  "8.7": {
    "title": "可靠性与故障恢复",
    "terms": [
      "API",
      "Prompt",
      "Token"
    ]
  },
  "8.8": {
    "title": "安全：把模型当作不可信决策者",
    "terms": [
      "Agent",
      "HTML",
      "Injection",
      "LLM",
      "OWASP",
      "Prompt",
      "SQL",
      "Shell"
    ]
  },
  "8.9": {
    "title": "LLMOps 与 AgentOps：建立持续改进闭环",
    "terms": [
      "Agent",
      "AgentOps",
      "Embedding",
      "LLM",
      "LLMOps",
      "Prompt",
      "Span",
      "Trace"
    ]
  },
  "8.10": {
    "title": "上线前的一页检查表",
    "terms": [
      "Agent",
      "P95",
      "Prompt",
      "RAG",
      "Token",
      "vs"
    ]
  },
  "9.1": {
    "title": "多模态模型究竟多了什么",
    "terms": [
      "AI",
      "CLIP",
      "OCR",
      "Token",
      "contrastive",
      "encoder",
      "learning",
      "projector",
      "vision"
    ]
  },
  "9.2": {
    "title": "生成图片：从噪声中逐步还原",
    "terms": [
      "Conditioning",
      "Control",
      "Guidance",
      "Inpainting",
      "LoRA",
      "Outpainting",
      "Prompt",
      "Seed",
      "denoising",
      "diffusion",
      "latent",
      "model",
      "steps"
    ]
  },
  "9.3": {
    "title": "语音、音乐和视频",
    "terms": [
      "ASR",
      "TTS",
      "WER",
      "consistency",
      "model",
      "temporal",
      "vocoder",
      "world"
    ]
  },
  "9.4": {
    "title": "多模态应用的正确拆法",
    "terms": [
      "OCR"
    ]
  },
  "10.1": {
    "title": "为什么 AI 喜欢 GPU",
    "terms": [
      "AI",
      "BF16",
      "CPU",
      "CUDA",
      "Cache",
      "Decode",
      "FLOPS",
      "FP16",
      "FP32",
      "FP8",
      "GPU",
      "INT4",
      "INT8",
      "KV",
      "NVIDIA",
      "Prefill",
      "Token",
      "VRAM",
      "compute"
    ]
  },
  "10.2": {
    "title": "延迟、吞吐与成本是一组三角关系",
    "terms": [
      "GPU",
      "TPOT",
      "TTFT",
      "Token",
      "batching",
      "decoding",
      "speculative"
    ]
  },
  "10.3": {
    "title": "MoE、模型路由与缓存：三种层次的节省",
    "terms": [
      "API",
      "Experts",
      "KV",
      "Mixture",
      "MoE",
      "Prompt",
      "Token",
      "of"
    ]
  },
  "10.4": {
    "title": "量化、蒸馏与模型压缩",
    "terms": [
      "Face",
      "Hugging",
      "PTQ",
      "QAT",
      "distillation",
      "pruning",
      "quantization",
      "sparsity"
    ]
  },
  "10.5": {
    "title": "本地部署、云 API 与混合架构",
    "terms": [
      "API",
      "GPU",
      "Token"
    ]
  },
  "10.6": {
    "title": "“开源模型”不一定真的开源",
    "terms": [
      "AI",
      "API",
      "OSI",
      "SLA",
      "open",
      "weights"
    ]
  },
  "11.1": {
    "title": "从“模型会答错”到完整风险地图",
    "terms": [
      "AI",
      "Govern",
      "Manage",
      "Map",
      "Measure",
      "NIST",
      "Profile",
      "RMF"
    ]
  },
  "11.2": {
    "title": "提示词注入与 Agent 权限",
    "terms": [
      "Agent",
      "PDF",
      "SQL",
      "guardrails",
      "injection",
      "prompt"
    ]
  },
  "11.3": {
    "title": "隐私与数据治理",
    "terms": [
      "AI",
      "data",
      "lineage"
    ]
  },
  "11.4": {
    "title": "版权问题要拆成三道题",
    "terms": [
      "AI"
    ]
  },
  "11.5": {
    "title": "透明度、标识与合规不是一张证书",
    "terms": [
      "AI",
      "EU",
      "IEC",
      "ISO",
      "Regulation"
    ]
  },
  "12.1": {
    "title": "先分清四个阶段：补全、对话、编辑与智能体",
    "terms": [
      "AI"
    ]
  },
  "12.2": {
    "title": "它们以什么形态进入工作流",
    "terms": [
      "AI",
      "Agent",
      "Ask",
      "CI",
      "CLI",
      "Claude",
      "Code",
      "Codex",
      "Copilot",
      "Cursor",
      "Diff",
      "Git",
      "GitHub",
      "IDE",
      "Issue",
      "Manual",
      "Pull",
      "Request",
      "Worktree"
    ]
  },
  "12.3": {
    "title": "Cursor、Claude Code 与 Codex 应该怎样理解",
    "terms": [
      "Claude",
      "Code",
      "Codex",
      "Cursor"
    ]
  },
  "12.4": {
    "title": "Context Engineering：让智能体看见正确的项目",
    "terms": [
      "Context",
      "Cursor",
      "Diff",
      "Engineering",
      "Git"
    ]
  },
  "12.5": {
    "title": "Rules、Instructions 与项目记忆",
    "terms": [
      "AGENTS",
      "API",
      "Claude",
      "Code",
      "Codex",
      "Cursor",
      "Instructions",
      "Lint",
      "Rules",
      "md"
    ]
  },
  "12.6": {
    "title": "怎样写一个适合编码智能体的任务",
    "terms": [
      "API",
      "Diff"
    ]
  },
  "12.7": {
    "title": "Plan、Agent、Review：模式代表不同授权",
    "terms": [
      "Agent",
      "Ask",
      "Diff",
      "Plan",
      "Review"
    ]
  },
  "12.8": {
    "title": "MCP、Skills、Hooks 和子智能体分别解决什么",
    "terms": [
      "AI",
      "Agent",
      "Context",
      "Hook",
      "Hooks",
      "MCP",
      "Model",
      "Plugin",
      "Protocol",
      "Skills"
    ]
  },
  "12.9": {
    "title": "Git、Worktree 与可恢复性",
    "terms": [
      "Diff",
      "Git",
      "Worktree"
    ]
  },
  "12.10": {
    "title": "验收 AI 代码：输出不是证据",
    "terms": [
      "AI",
      "Diff",
      "Lint"
    ]
  },
  "12.11": {
    "title": "权限、安全和隐私",
    "terms": [
      "AI",
      "Cursor",
      "Issue",
      "MCP"
    ]
  },
  "12.12": {
    "title": "怎样选择工具",
    "terms": [
      "Bug",
      "Diff"
    ]
  },
  "12.13": {
    "title": "三类人怎样开始",
    "terms": [
      "AI",
      "Git",
      "HTTP",
      "Hook",
      "Skill"
    ]
  },
  "12.14": {
    "title": "常见误区",
    "terms": [
      "AI",
      "Agent",
      "Agents",
      "Anthropic",
      "App",
      "Background",
      "CLI",
      "Cheat",
      "Claude",
      "Code",
      "Codex",
      "Context",
      "Copilot",
      "Cursor",
      "Customization",
      "Getting",
      "GitHub",
      "Introducing",
      "Mode",
      "Model",
      "OpenAI",
      "Overview",
      "Protocol",
      "Reference",
      "Rules",
      "Security",
      "Setup",
      "Sheet",
      "Started",
      "Using",
      "and",
      "the"
    ]
  },
  "13.1": {
    "title": "用交付物理解岗位",
    "terms": [
      "AI",
      "API",
      "RAG"
    ]
  },
  "13.2": {
    "title": "三条主路线",
    "terms": [
      "AI",
      "Agent",
      "CNN",
      "CUDA",
      "Cache",
      "Demo",
      "Embedding",
      "GPU",
      "Git",
      "HTTP",
      "JSON",
      "KV",
      "Linux",
      "NumPy",
      "PyTorch",
      "Python",
      "RAG",
      "Token",
      "Transformer",
      "TypeScript"
    ]
  },
  "13.3": {
    "title": "一套可执行的 12 周起步方案",
    "terms": [
      "AI",
      "API",
      "Demo",
      "JSON",
      "RAG"
    ]
  },
  "13.4": {
    "title": "怎样判断一项 AI 技术值不值得学",
    "terms": [
      "AI",
      "Benchmark"
    ]
  },
  "13.5": {
    "title": "行业判断：能力在商品化，问题定义更值钱",
    "terms": [
      "AI",
      "Agent"
    ]
  },
  "13.6": {
    "title": "给入门者的最后一张检查表",
    "terms": [
      "AI",
      "GPU",
      "Token"
    ]
  }
};
