/** English copy for interface text and teaching demonstrations. Chinese keys are stable source copy. */
export const englishUi: Record<string, string> = {
  '《': '', '》': ' ', '。': '.',
  'AI World 首页': 'AI World home',
  '一张可以走进去的 AI 地图': 'An AI world you can explore',
  '主导航': 'Main navigation',
  '世界地图': 'Lab map',
  '探索护照 ': 'Passport ',
  '← 世界全图': '← World map',
  '原来，AI 的世界是这样连起来的。': 'Discover how the world of AI connects.',
  '从一个 Token 出发。穿过山谷，在动手探索中，把复杂的东西拆开看。': 'Start with a token. Explore the valleys and discover the ideas behind AI, one step at a time.',
  '直达量化矿山 ': 'Visit the quantization mine ',
  'AI 大陆互动地图': 'Interactive AI continent map',
  ' AI 大陆': ' AI Continent',
  '可拖动地图。点击地点探索；使用缩放按钮或滚轮缩放；聚焦地图空白后用方向键移动。': 'Drag to explore. Select a landmark, use the zoom buttons or scroll wheel, or focus the map background and move with the arrow keys.',
  ' 拖动地图 · 滚轮缩放 · 点击地点': ' Drag to explore · Scroll to zoom · Select a landmark',
  '地图视图控制': 'Map controls',
  '缩小地图': 'Zoom out',
  '放大地图': 'Zoom in',
  '重置地图': 'Reset map',
  '地点探索': 'Explore this landmark',
  '探索路线': 'Exploration route',
  '一条路，五个发现': 'One route. Five discoveries.',
  '已发现': 'Discovered',
  '待探索': 'To explore',
  ' 小淘带你探索': ' Guided by Xiaotao',
  'AI WORLD · 可玩概念原型 ': 'AI WORLD · Interactive learning prototype ',
  '关于这张地图 ↗': 'About this map ↗',
  '关闭弹窗': 'Close dialog',
  '关于 Token，哪句话更准确？': 'Which statement about tokens is more accurate?',
  '一个 Token 永远等于一个汉字': 'One token always equals one word',
  'Token 是模型处理文本的单位': 'Tokens are the units a model uses to process text',
  '发现了！分词方式由具体 tokenizer 决定，一个字和一个 Token 并不总是一一对应。': 'You found it! The tokenizer determines the split. A character or word does not always correspond to one token.',
  '哪一对表达，在语义上更接近？': 'Which pair is closer in meaning?',
  '“小猫”与“猫咪”': '“cat” and “kitten”',
  '“小猫”与“显卡”': '“cat” and “GPU”',
  '发现了！在合适的语义嵌入空间里，意思相关的表达通常更接近；具体距离取决于模型。': 'You found it! Related expressions are often closer in a suitable embedding space. The actual distances depend on the model.',
  '注意力在这里帮助模型做什么？': 'What does attention help the model do here?',
  '根据上下文关联信息': 'Connect information using context',
  '只看离它最近的一个字': 'Look only at the nearest word',
  '发现了！注意力让当前位置能够结合上下文。图里的连线是机制示意，并非实测权重。': 'You found it! Attention lets a position use information from context. These lines illustrate the mechanism; they are not measured weights.',
  '模型接出“蓝”，说明了什么？': 'What does predicting “blue” tell us?',
  '代表这句话必然是真的': 'The sentence must be true',
  '只是模型给出了下一步预测': 'The model has made a next-token prediction',
  '发现了！续写得流畅，并不保证事实正确。重要结论仍然需要核实来源。': 'You found it! A fluent continuation does not guarantee factual accuracy. Check reliable sources for important claims.',
  '今天': 'Today', '天气': ' the weather', '很好': ' is nice',
  '切块示意 · 不对应真实 tokenizer 输出': 'Illustrative chunks · Not the output of a real tokenizer',
  '语义空间示意，小猫和猫咪较近，显卡较远': 'Illustrative semantic space: cat and kitten are close, GPU is farther away',
  '小猫': 'cat', '猫咪': 'kitten', '显卡': 'GPU',
  '位置为教学示意 · 无实测向量值': 'Illustrative positions · No measured embeddings',
  '小猫累了，因为': 'The cat was tired because ',
  '它': 'it', '跑了很久。': ' had been running.',
  '“它”指向谁？把上下文连起来。': 'What does “it” refer to? Connect the context.',
  '今天的天空很': 'Today the sky is ', '蓝': 'blue',
  '上下文': 'Context', '下一步预测': 'Next prediction',
  '固定续写示例 · 未连接真实模型': 'Fixed example · No live model connected',
  'SIDE QUEST / 支线实验': 'SIDE QUEST / EXPERIMENT',
  '已盖章 ✓': 'Stamped ✓', '探索中': 'Exploring', '向导小淘': 'Xiaotao, your guide',
  '带上 70B 模型去矿山。调整精度，看看内存预算发生了什么。': 'Bring a 70B model to the mine. Change its precision and see what happens to the memory budget.',
  '想一想 · 带走一个发现': 'TRY A QUESTION · TAKE A DISCOVERY WITH YOU',
  '前往下一站': 'Next landmark', '先去下一站看看': 'Explore the next landmark',
  '教学估算只检查内存预算，不保证能部署，也不代表性能。': 'This teaching estimate checks memory only. It does not guarantee deployment or predict performance.',
  '再观察一下上面的示意，换一个答案试试。': 'Look at the illustration again and try another answer.',
  '在知识地图中继续读这一章 ↗': 'Read the related chapter in the atlas ↗',
  '任务：把 70B 装进预算': 'Mission: fit 70B into the budget',
  '选择 48 GiB，保留至少 32K 上下文。': 'Choose 48 GiB and keep at least 32K context.',
  '每个参数，留几位？': 'How many bits per parameter?',
  '上下文长度': 'Context length', '内存预算': 'Memory budget',
  '检查我的方案 ': 'Check my plan ',
  '估算怎么算？查看假设与来源 ↗': 'How is this calculated? Assumptions and sources ↗',
  '还差 ': 'Over budget by ',
  ' GiB。试试降低权重精度，或缩短上下文。': ' GiB. Try lower weight precision or a shorter context.',
  '估算在所选预算内！本关还需要：48 GiB 预算、至少 32K 上下文。': 'The estimate fits your budget! This mission also requires a 48 GiB budget and at least 32K context.',
  '任务完成！你为权重、KV Cache 和额外开销留出了空间。真实部署仍要实测。': 'Mission complete! You left room for weights, the KV cache, and overhead. Real deployment still needs measurement.',
  '预计占用 ': 'Estimated usage ', '预算内': 'Within budget', '超出预算': 'Over budget',
  '权重 ': 'Weights ', ' GiB，额外开销 ': ' GiB, overhead ', ' GiB，总预算 ': ' GiB, total budget ',
  '其他 ': 'Other ', ' GiB 权重': ' GiB of weights',
  '探索护照集齐了！你已经连接起五个 AI 概念。': 'Passport complete! You have connected five AI concepts.',
  '新发现已收入探索护照': 'A new discovery has been added to your passport',
  '把估算拆开看': 'Inside the estimate', '这是一个 ': 'This is a ',
  '70 × 10⁹ 参数的教学模型': 'teaching model with 70 × 10⁹ parameters',
  '。我们只做内存预算练习，未运行推理，也没有测量吞吐或速度。': '. This is a memory-budget exercise. We have not run inference or measured throughput or speed.',
  '权重内存': 'Weight memory',
  '参数量 × 每参数位数 ÷ 8 ÷ 2³⁰。32 / 16 / 8 / 4 bit 表示示意存储位宽，不代表任意模型都支持这些格式。': 'Parameter count × bits per parameter ÷ 8 ÷ 2³⁰. The 32 / 16 / 8 / 4-bit options are illustrative storage widths; not every model supports every format.',
  '2 × 80 层 × 8 个 KV 头 × 128 维 × 上下文 tokens × 2 bytes ÷ 2³⁰。采用 Llama 70B 系列的 GQA 维度，batch ': '2 × 80 layers × 8 KV heads × 128 dimensions × context tokens × 2 bytes ÷ 2³⁰. Uses Llama 3.1 70B-style GQA dimensions, batch ',
  ' 1，KV 为 FP16。上下文表示已填满的缓存长度。': ' 1, with FP16 KV. Context means the occupied cache length.',
  '额外开销：固定假设 3 GiB': 'Overhead: an assumed 3 GiB reserve',
  '只是课堂假设，不是测量结果。量化元数据、激活、临时缓冲区和框架预留在实际部署中都会变化；固定值不能保证覆盖它们。': 'This is a teaching assumption, not a measurement. Quantization metadata, activations, temporary buffers and runtime reserves vary in real deployments; a fixed reserve cannot guarantee coverage.',
  '单位与边界': 'Units and limits',
  ' 10⁹ bytes。70B 的 4-bit 理想权重为 35 GB ≈ 32.6 GiB。硬件标称容量、系统可用内存、质量损失和兼容性都需另行核对。': ' 10⁹ bytes. Ideal 4-bit weights for 70B take 35 GB ≈ 32.6 GiB. Hardware capacity, available memory, quality loss and compatibility require separate checks.',
  '每个发现，都算数。': 'Every discovery counts.', '你已经收集了 ': 'You have collected ',
  ' 个发现。探索进度保存在当前浏览器。': ' discoveries. Progress is saved in this browser.',
  '继续探索 →': 'Keep exploring →',
  '解答每站的问题，或完成矿山的预算任务，就能盖章。所有地点都可以自由访问。': 'Answer each question or complete the memory-budget mission to earn stamps. Every landmark is freely accessible.',
  '知识也可以是一片大陆。': 'Knowledge can be a world to explore.',
  '这是 Tao 创作的 AI World 小型概念原型，小淘是你的探索向导。第一版用五个地点，试着把“读懂一个概念”变成“亲手发现一件事”。': 'AI World is a learning prototype created by Tao, with Xiaotao as your guide. These five landmarks turn concepts into small discoveries you can make yourself.',
  '地理和路线是学习比喻，不是严格的架构依赖。五站都能自由探索；量化矿山用简化计算展示运行内存的组成。': 'The geography and routes are learning metaphors, not strict architectural dependencies. All five landmarks are open; the quantization mine uses simplified calculations to explain runtime memory.',
  '地图支持拖动、滚轮缩放、触屏拖动；可使用 Tab 选择地点、Enter 打开，以及缩放按钮。聚焦地图空白后用方向键移动。': 'Drag with a mouse or touch, scroll to zoom, or use the zoom buttons. Use Tab to focus landmarks and Enter to open them. Focus the map background to pan with the arrow keys.',
  '本地 demo · 不需要账号 · 不调用 AI API': 'Local demo · No account needed · No AI API calls',
  'Created by Tao · Guide: 小淘': 'Created by Tao · Guide: Xiaotao',
  'AI World · 探索 AI 入行知识地图': 'AI World · An interactive guide to AI',
  '世界全图': 'World map', '实验小径 ': 'Lab trail ',
  '从模型的诞生，走到你的第一份作品。': 'From a model’s first steps to your first project.',
  '沿着《': 'Explore four regions with ',
  '》探索四片区域。每个概念，都有它解决的问题和使用的边界。': '. Discover the problem each concept solves, and where its limits lie.',
  '章': 'chapters', '知识点': 'topics', '突出显示地图区域': 'Highlight a map region', '全世界': 'All regions',
  '搜索知识地图': 'Search the atlas', '搜索 Token、RAG、MCP…': 'Search tokens, RAG, MCP…',
  '十三章 AI 世界地图': 'AI world map with thirteen chapters', '✥ AI 世界全图': '✥ AI WORLD ATLAS',
  '世界地图。Tab 选择章节，Enter 打开；空白处方向键平移，滚轮或按钮缩放。': 'World map. Use Tab to select a chapter and Enter to open it. Focus the background to pan with arrow keys; use the wheel or buttons to zoom.',
  '拖动探索 · 点击地标 · Enter 打开章节': 'Drag to explore · Select a landmark · Enter to read',
  '放大查看地标 · 点击探索': 'Zoom in for landmarks · Tap to explore',
  '缩小世界地图': 'Zoom out on world map', '放大世界地图': 'Zoom in on world map', '重置世界地图': 'Reset world map',
  '章节介绍': 'Chapter overview', '学习路线': 'Learning routes',
  '从你的目标，选择一条路线。': 'Choose a route for your goal.', '学习方向 ': 'Learning direction ',
  '内容依据 ': 'Adapted from ', '原文结构 → 地图探索 → 理解挑战 ': 'Source outline → Map exploration → Learning challenges ',
  '内容与版本说明 ↗': 'Content and edition notes ↗',
  '世界地图与实验小径 · 交互学习原型': 'World map and lab trail · Interactive learning prototype',
  '关闭探索窗口': 'Close exploration window', '等待发现': 'Waiting to be discovered',
  '你将带走的三个发现': 'Three discoveries to take with you',
  ' 个知识点': ' topics', '1 个理解挑战': '1 learning challenge', ' 处实验': ' lab(s)',
  '进入这一章 ': 'Explore this chapter ', '">去': '">Try ', '动手试试 ↗': ' ↗',
  '先想一个你要解决的问题，再读概念。地图上的道路是学习路线，不是必须依次解锁的关卡。': 'Start with a question you want to answer. The paths suggest learning routes; you can explore every landmark freely.',
  '本章理解挑战已完成 ✓': 'Chapter challenge completed ✓',
  '十三章挑战完成！带着地图，去做你的作品。': 'All thirteen challenges completed! Take your map and build something.',
  '第 ': 'Chapter ', ' 章的发现，已收入探索护照。': ' has been added to your passport.',
  '原文第 ': 'Source chapter ', ' 章 · ': ' · ', ' 个知识点 · ': ' topics · ',
  '本章知识点目录': 'Chapter contents', '本章探索': 'IN THIS CHAPTER', '✧ 理解挑战': '✧ Learning challenge',
  '放进一个真实问题': 'TRY A REAL SCENARIO', '依据原文 ': 'Adapted from source section ', ' 节整理': '',
  '本章理解挑战': 'Chapter learning challenge', '回答正确后，为探索护照盖章。': 'Answer correctly to earn a passport stamp.',
  '把概念放进实验': 'TRY IT IN A LAB', '继续阅读 · 原文所列资料': 'FURTHER READING · SOURCES FROM THE ORIGINAL GUIDE',
  '探索可以自由跳转': 'Explore in any order', '下一章：': 'Next chapter: ', '回到起点，重看全貌': 'Return to the beginning',
  '再想一下：这个方案改变了什么，又没有保证什么？可以回到知识点再看看。': 'Think again: what does this change, and what does it not guarantee? Revisit the explanation if you need a hint.',
  '你想弄懂什么？': 'What would you like to understand?', '试试 RAG、微调、MCP 或职业': 'Try RAG, fine-tuning, MCP or careers',
  '搜索章节和知识点': 'Search chapters and topics', '找到 ': 'Found ', ' 个相关知识点': ' related topics', '全部 ': 'All ',
  ' 个知识点，输入关键词缩小范围。': ' topics. Type a keyword to narrow the search.',
  '这张地图里暂时没有匹配项。试试更短的关键词，或回到全图选择章节。': 'No matching topics yet. Try a shorter keyword or choose a chapter on the map.',
  '每个发现，都留下一个坐标。': 'Give every discovery a place on your map.', '已完成 ': 'Completed ',
  ' 章理解挑战。实验小径另有 ': ' chapter challenges. Your lab trail also has ',
  ' 枚印章；原有进度已经保留。': ' stamps. Your existing progress is preserved.',
  '去探索 →': 'Explore →',
  '印章表示完成了这里的理解挑战，不等于已经掌握全部知识。进度仅保存在当前浏览器。': 'A stamp records completion of a challenge, not mastery of all the material. Progress is saved only in this browser.',
  '一份知识地图，两种探索方式。': 'One atlas. Two ways to explore.',
  '内容依据《': 'Adapted from ', '》，保留原文的四部分、十三章与 ': ', preserving its four parts, thirteen chapters and ',
  '，保留原文的四部分、十三章与 ': ', preserving its four parts, thirteen chapters and ',
  ' 个编号小节。每节改写为问题、解释与具体例子，并增加一个章节理解挑战。': ' numbered topics. Each topic includes an explanation and a concrete example, with one learning challenge per chapter.',
  '知识大陆帮助你建立全貌；实验小径保留了 Token、向量、注意力、续写与量化的五站互动。两种方式互相连接，可以自由跳转。': 'The atlas gives you the big picture. The lab trail explores tokens, embeddings, attention, next-token prediction and quantization. Move freely between the two.',
  '原文资料核查日期为 2026 年 8 月 31 日。此版是学习内容改编，未逐条重新核验所有外链及动态产品信息。产品能力、价格、许可和适用规则需要在使用时核实。': 'The source guide was reviewed on August 31, 2026. This edition is a learning adaptation, not a fresh verification of every link or changing product detail. Check capabilities, prices, licenses and applicable rules when you use them.',
  '原文的图表没有作为图片粘贴进网页，当前地图与实验图解均由代码绘制。地貌表达学习关系，不是严格的 AI 架构依赖。': 'The original figures are not embedded as screenshots. Maps and experiment diagrams are drawn in code. The geography illustrates learning relationships, not strict AI architecture dependencies.',
  '进度保存在当前浏览器，无需登录。': 'Progress stays in this browser. No sign-in required.',
  'Token 村': 'Token Village', '向量河谷': 'Embedding Valley', '注意力山脉': 'Attention Range',
  '大模型之城': 'LLM City', '量化矿岛': 'Quantization Mine',
  'AI World 交互探索地图：Token 村、向量河谷、注意力山脉、大模型之城与量化矿岛': 'Interactive AI World map: Token Village, Embedding Valley, Attention Range, LLM City and Quantization Mine',
  '探索 Token 村：文字如何变成模型的输入': 'Explore Token Village: how text becomes model input',
  '探索向量河谷：词语如何拥有位置与含义': 'Explore Embedding Valley: representing words as vectors',
  '探索注意力山脉：Token 怎样彼此交换信息': 'Explore Attention Range: how tokens exchange information',
  '探索大模型之城：从预测下一个 Token 到对话': 'Explore LLM City: from next-token prediction to conversation',
  '探索量化矿岛：让一个 70B 模型装进显存': 'Explore Quantization Mine: estimate memory for a 70B model',
  '数 据 海': 'DATA SEA', '启程港': 'Starting Harbor', '学习原野': 'Learning Fields', '训练工坊': 'Training Works',
  '提示驿站': 'Prompt Station', '检索森林': 'Retrieval Forest', '智能体城': 'Agent City', '评测灯塔': 'Evaluation Beacon',
  '多模态海岸': 'Multimodal Coast', '算力矿山': 'Compute Mine', '守望堡垒': 'Safety Citadel',
  '编码工坊': 'Coding Workshop', '职业远航港': 'Career Harbor',
  '模型起源大陆': 'Model Origins', '从 AI 基础到大模型训练': 'From AI foundations to model training',
  '应用群岛': 'Application Isles', '从提示到智能体与评测': 'From prompts to agents and evaluation',
  '技术与治理海岸': 'Systems & Governance', '多模态、算力与安全': 'Multimodality, compute and safety',
  '实践远航湾': 'Builder’s Bay', '从动手编码到职业探索': 'From coding projects to career exploration',
  '探索第 ': 'Explore chapter ', ' 章：': ': ',
  'AI World 知识世界：四片大陆、十三个可探索地点。使用 Tab 选择地点，回车打开。': 'AI World atlas: four regions and thirteen landmarks. Use Tab to select a landmark and Enter to open it.',
  '数据海': 'DATA SEA',
  '一句话从这里出发。分词器先把文字转换成一串 token ID，模型才能处理它。': 'A sentence starts here. A tokenizer turns text into token IDs so a model can process it.',
  'Token 不一定是一个字或一个词。切法取决于分词器，标点和空格也可能参与其中。': 'A token is not necessarily a character or a word. The split depends on the tokenizer; punctuation and spaces can be part of tokens too.',
  '拆开一句话，看看它如何变成小块。': 'Take a sentence apart and see how it becomes smaller pieces.', '向量谷': 'Embedding Valley',
  'Token ID 在这里找到对应的向量：一组可以参与计算的数字。模型随后继续结合上下文更新表示。': 'Each token ID maps to a vector: numbers the model can compute with. Later layers update these representations using context.',
  '这张二维小地图只是示意。真实向量通常有很多维，相似度也取决于模型和任务。': 'This two-dimensional map is illustrative. Real embeddings usually have many dimensions, and similarity depends on the model and task.',
  '看看词语在示意地图里如何靠近彼此。': 'See how related words sit near one another on this illustrative map.',
  '注意力让当前位置参考相关上下文；前馈网络等模块再继续加工这些信息，多层配合构成 Transformer。': 'Attention lets a position draw on relevant context. Feed-forward networks and other components process that information; many such layers form a Transformer.',
  '注意力不是人的意识。在生成式语言模型中，当前位置通常只能参考自己和前面的 token。': 'Attention is not human awareness. In a causal language model, a position typically attends only to itself and preceding tokens.',
  '点亮一句话中的联系，找出有用的上下文。': 'Connect parts of a sentence and find the context that matters.', '大模型城': 'LLM City',
  '生成式语言模型根据已有上下文，计算下一个 token 的分布，再按生成策略选出一个，反复续写。': 'An autoregressive language model computes a distribution over the next token from the context, selects one using a decoding strategy, and repeats.',
  '接得顺不等于说得对。语言模型会犯错，重要事实仍需要可靠来源来核实。': 'A smooth continuation can still be wrong. Language models make mistakes; verify important facts using reliable sources.',
  '试着续写一句话，观察多个可能的下一步。': 'Explore how a sentence can continue in different ways.', '量化矿山': 'Quantization Mine',
  '70B 表示约 700 亿个参数。降低权重的存储位数可以缩小权重占用，但运行时还要给缓存等内容留位置。': '70B means roughly 70 billion parameters. Using fewer bits to store weights reduces their size, but runtime memory must also hold the cache and other data.',
  '4-bit 改变的是权重的表示精度，不是把 70B 变成更少的参数；量化也可能影响输出质量。': '4-bit changes how weights are represented, not the number of parameters. Quantization can also affect output quality.',
  '调节精度、上下文和内存预算，让教学估算落入预算。': 'Adjust precision, context and memory budget until the teaching estimate fits.',
  'Meta · Llama 3.1 70B 架构参数': 'Meta · Llama 3.1 70B architecture',
  'Hugging Face · KV Cache 的工作方式': 'Hugging Face · How the KV cache works',
  'Hugging Face · 权重量化与数据类型': 'Hugging Face · Weight quantization and data types',
  '模型从哪里来': 'Where models come from',
  '从 AI 的系统坐标，到学习、Transformer 与训练生命周期。': 'Find your bearings in AI, then explore learning, Transformers and the training lifecycle.',
  '能力怎样进入产品': 'From capability to product',
  '用上下文、检索、工具和评测，把模型接入真实任务。': 'Connect models to real tasks with context, retrieval, tools and evaluation.',
  '重要专题': 'Essential systems topics',
  '多模态、算力、开源与安全，决定系统的能力和边界。': 'Multimodality, compute, openness and safety shape a system’s capabilities and limits.',
  '进入真实工作': 'Into real projects',
  '从管理编码智能体，到选择方向、完成作品与形成判断。': 'Manage coding agents, choose a direction, finish a project and develop your judgment.',
  '完整探索': 'Complete expedition',
  '按原文顺序建立完整地图，再决定在哪个方向深入。': 'Follow the source guide to build a complete picture, then choose where to go deeper.',
  '产品与业务': 'Product & business',
  '先把系统拆清楚，再看知识、行动、评测、治理和价值。': 'Understand the system first, then explore knowledge, actions, evaluation, governance and value.',
  '应用开发': 'Application building',
  '从模型直觉出发，把 Prompt、RAG 和 Agent 接进一个真实项目。': 'Build an intuition for models, then use prompts, RAG and agents in a real project.',
  '算法与模型': 'Algorithms & models',
  '深入学习过程、模型架构、训练、多模态和计算资源。': 'Go deeper into learning, model architecture, training, multimodality and compute.',
  '系统与基础设施': 'Systems & infrastructure',
  '先建立模型直觉，再关注生产化、资源和开发工作流。': 'Start with model intuition, then focus on production, resources and development workflows.',
  'AI 入行知识地图': 'AI Entry Knowledge Map',
};
